title: Earth Data Analytics
author: Ed Chan
email: "ed.chan at colorado.edu"

description: >
  Technical Consultant exploring Earth Data Analytics. My opinions are my own.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/eggvoice" }
    - { platform: twitter, user_url: "https://twitter.com/myeggvoice" }
