title: Earth Data Analytics
author:
  name: Ed Chan

description: >
  Technical Consultant exploring Earth Data Analytics. My opinions are my own.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
